# Generated by Django 5.0.3 on 2024-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonthlyCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycategory',
            name='month',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='monthlycategory',
            name='year',
            field=models.IntegerField(default=4),
        ),
    ]
