# Generated by Django 5.0.3 on 2024-03-16 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0003_alter_budget_user'),
        ('CategoryGroup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget'),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
