# Generated by Django 5.0.3 on 2024-03-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryGroup', '0002_alter_categorygroup_budget_alter_categorygroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
