# Generated by Django 5.0.3 on 2024-03-17 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Budget', '0003_alter_budget_user'),
        ('CategoryGroup', '0003_categorygroup_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_amount', models.FloatField()),
                ('order', models.IntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget')),
                ('category_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CategoryGroup.categorygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
