# Generated by Django 5.0.3 on 2024-03-14 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Budget', '0002_alter_budget_budget_id_alter_budget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='budget',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Budget.budget'),
        ),
    ]
