# Generated by Django 5.0.3 on 2024-03-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_account_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Checking', 'Checking'), ('Investment', 'Investment'), ('Credit', 'Credit')], max_length=50, null=True),
        ),
    ]
