# Generated by Django 5.0.3 on 2024-04-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_account_budget_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(blank=True, default='Budget', max_length=50),
        ),
    ]
